name: Continuous Integration

on:
  push:
env:
  MAVEN_SERVER_USERNAME: ${{ secrets.MAVEN_SERVER_USERNAME }}
  MAVEN_SERVER_PASSWORD: ${{ secrets.MAVEN_SERVER_PASSWORD }}

permissions:
  contents: read

jobs:
  maven-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
          server-id: github
          server-username: MAVEN_SERVER_USERNAME
          server-password: MAVEN_SERVER_PASSWORD
      - name: Verify build
        run: mvn -B verify